packages/react-forms/src/Button/index.js, packages/react-forms/src/InputCheckbox/index.js, packages/react-forms/src/InputDate/index.js, packages/react-forms/src/InputRadio/index.js, packages/react-forms/src/TextArea/index.js, packages/react-layouts/src/Breadcrumb/index.js, packages/react-mouse-outside/src/index.js, packages/react-mouse-outside/src/index.test.js, packages/react-tabs-provider/src/index.md
Improves the react-mouse-outside types and fixes some docs
- @quid/react-mouse-outside
[committing-and-publishing]: https://github.com/quid/refraction/blob/master/CONTRIBUTING.md
=> Better types and docs

packages/react-layouts/package.json, packages/react-layouts/src/Tabs/Tab/index.js, packages/react-layouts/src/Tabs/TabPanel/index.js, packages/react-layouts/src/Tabs/Tabs.md, packages/react-layouts/src/Tabs/__snapshots__/index.test.js.snap, packages/react-layouts/src/Tabs/index.js, packages/react-layouts/src/Tabs/index.test.js, packages/react-layouts/src/index.js, packages/react-layouts/src/index.test.js
Added Tabs component to react-layouts
=> feat: adds tabs to react-layouts

packages/react-layouts/package.json, packages/react-layouts/src/Modal/ActionBar.js, packages/react-layouts/src/Modal/Centerer.js, packages/react-layouts/src/Modal/Header.js, packages/react-layouts/src/Modal/Modal.md, packages/react-layouts/src/Modal/__snapshots__/index.test.js.snap, packages/react-layouts/src/Modal/importanceTypes.js, packages/react-layouts/src/Modal/index.js, packages/react-layouts/src/Modal/index.test.js, yarn.lock
=> feat: adds modal component to react layouts

packages/react-dropdown/src/Categories.js, packages/react-dropdown/src/Items.js, packages/react-dropdown/src/dropdownTypes.js, packages/react-dropdown/src/index.js, packages/react-dropdown/src/index.test.js
Introduces `item.children` and `category.hidden`option.
=> feat: support for custom item children for the dropdown

.travis.yml
This ensures the packages compile correctly before we merge them into master.
=> build: run build scripts on PRs

packages/react-layouts/src/Breadcrumb/index.js
adds navlink to breadcrumbs
- @quid/react-layout
=> feat: adds navlink to breadcrumbs

packages/react-layouts/src/index.js, packages/react-layouts/src/index.test.js
=> fix: export Modal

packages/react-layouts/src/NavBar/__snapshots__/index.test.js.snap, packages/react-layouts/src/NavBar/index.js, packages/react-layouts/src/index.js, packages/react-layouts/src/index.test.js
The paddings and alignment were off.
=> fix: navbar styling issues

package.json, packages/react-core/src/Button/Button.md, packages/react-core/src/Icon/Icon.md, packages/react-dropdown/src/index.md, packages/react-forms/src/InputGroup/InputGroup.md, packages/react-forms/src/InputRange/index.test.js, packages/react-forms/src/InputText/InputText.md, packages/react-forms/src/Label/Label.md, packages/react-forms/src/TextArea/TextArea.md, packages/react-forms/src/TextArea/index.js, packages/react-forms/src/TextArea/index.test.js, packages/react-invalid-handler/README.md, packages/react-layouts/src/Breadcrumb/__snapshots__/index.test.js.snap, packages/react-layouts/src/Breadcrumb/index.test.js, packages/react-layouts/src/Footer/Footer.md, packages/react-layouts/src/Modal/Modal.md, packages/react-layouts/src/Modal/index.test.js, packages/react-layouts/src/Tabs/Tabs.md, packages/react-tabs-provider/src/index.md, src/components/ComponentsListRenderer.js, src/components/Examples.js, src/components/SectionHeading.js, src/components/StyleGuide.js, styleguide.config.js, yarn.lock
Upgrades react-styleguidist and other "docs related" deps to latest version
N/A
=> chore: upgrade react styleguidist

.travis.yml, package.json, yarn.lock
=> chore: fix docs build

package.json, yarn.lock
Upgraded Flow to latest to get the most recent features and bug fixes
=> chore: upgrade flow to 0.96

packages/theme/README.md
Updated import path in the packages/theme example
- @quid/theme
=> docs: update packages/theme docs

.travis.yml, yarn.lock
Changes yarn version to latest in travis.
none
=> chore: upgrades yarn version in travis

packages/react-dropdown/src/index.js, packages/react-dropdown/src/index.md
Exports DropdownList for styling.
=> feat: exports DropdownList from Dropdown component

packages/react-dropdown/src/List.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap, packages/react-dropdown/src/index.test.js
Fixes missing styled component in DropdownList
=> fix: wraps DropdownList with styled

packages/react-layouts/src/Breadcrumb/index.js
Exports flow ContentProps from Breadcrumb component
=> feat: exports flow ContentProps from Breadcrumb component

packages/react-dropdown/src/index.md
=> docs: fixes broken react-dropdown examples

.travis.yml
I can't get #108 to work at the moment, so let's try to bump yarn to use the same version that's working for me locally
=> chore: upgrade Yarn

packages/react-core/src/Button/__snapshots__/index.test.js.snap, packages/react-core/src/Button/index.js, packages/react-core/src/Button/index.test.js, packages/react-forms/src/ButtonGroup/ButtonGroup.md, packages/react-forms/src/ButtonGroup/__snapshots__/index.test.js.snap, packages/react-forms/src/ButtonGroup/index.js, packages/react-forms/src/ButtonGroup/index.test.js, packages/react-forms/src/InputColor/index.js, src/components/Examples.js
This PR adds a new `ButtonGroup` component to be used together with the existing `Button` component.
=> ButtonGroup component

packages/react-expandable-table/src/index.js, packages/react-expandable-table/src/index.test.js, packages/react-expandable-table/src/styles.js
- @quid/react-expandable-table
=> feat: add light theme support to react-expandable-table

packages/react-dropdown/src/HighlightValue.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap
Add id in react-dropdown highlightValue component for automation test
=> chore: add id for dropdown item value for automation testing

packages/react-dropdown/package.json, packages/react-dropdown/src/Categories.js, packages/react-forms/src/index.test.js, packages/react-layouts/src/index.test.js, packages/theme/src/index.test.js, yarn.lock
refs: QUID-27512
- @quid/...
- @quid/...
=> fix: sorting issue on FireFox

packages/react-dropdown/src/Items.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap, packages/react-dropdown/src/index.test.js
change the selected color for react-dropdown
=> fix: rebrand | please update the outliers button and selected state color

.github/workflows/ci.yaml
=> chore: migrate ci/cd pipelines to github actions and argo cd

packages/react-dropdown/src/Items.js
=> fix: remove-unused-props
