packages/react-forms/src/InputDate/index.js, packages/react-mouse-outside/src/index.js, packages/react-mouse-outside/src/index.md, packages/react-mouse-outside/src/index.test.js
adds support for multiple refs for mouse outside
- @quid/react-mouse-outside
=> fix: adds support for multiple refs for mouse outside

packages/react-dropdown/src/MultiDownshift.js, packages/react-dropdown/src/MultiSelect.md, packages/react-dropdown/src/__mocks__/DropdownWrapper.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap, packages/react-dropdown/src/index.js, packages/react-dropdown/src/index.md, packages/react-dropdown/src/index.test.js, yarn.lock
Makes `clearSelection` work for dropdown. It is needed for further development of AF-473.
Adds support for being used as a controlled component. See example in the `index.md`.
Here is how to test clearSelection:
```js
const items = [
{ id: 10, label: 'One' },
{ id: 22, label: 'Two' },
{ id: 33, label: 'Three' },
{ id: 44, label: 'Four' },
{ id: 55, label: 'Four' },
{ id: 66, label: 'Three' },
{ id: 77, label: 'Four' },
{ id: 88, label: 'Three' },
{ id: 99, label: 'Four' },
{ id: 101, label: 'Three' },
{ id: 111, label: 'Four' },
{ id: 121, label: 'Three' },
{ id: 131, label: 'One' },
];
<Dropdown items={items} >
{({ getInputProps, clearSelection }) => <div><InputText readOnly {...getInputProps()} /><button onClick={clearSelection}>Clear selection</button></div>}
</Dropdown>;
```
- …
=> feat: adds clearSelection support for Dropdown

packages/react-dropdown/src/MultiDownshift.js, packages/react-dropdown/src/index.js, packages/react-dropdown/src/index.test.js
Simplifies the code removing `constructor`, un-needed explicit returns, making some types slightly clearer, and converting normal function methods into auto-bound arrow functions to make sure `this` is always the expected one
=> refactor: simplify MultiDownshift code

packages/react-dropdown/src/Items.js, packages/react-dropdown/src/dropdownTypes.js, packages/react-dropdown/src/index.test.js
Here is a simple test example what capability are we adding: [line 14](https://github.com/quid/refraction/blob/a1b2df91d67d06c8dfc17ed686694d8e570d55c9/packages/react-dropdown/src/index.test.js#L114)
=> feat: provides the original item as onChange argument at Dropdown

.travis.yml, packages/react-core/src/Button/__snapshots__/index.test.js.snap, packages/react-core/src/Button/index.js, packages/react-core/src/Button/index.test.js
This avoids accidental form submissions
Fixes default button type
- @quid/react-date-picker (will fix bug with accidental submit on month change)
=> fix: default Button to type=button

packages/react-date-picker/package.json
There was a missing dependency, this PR should fix it.
I will prepare another PR where I add a new Travis CI step to simulate a publish process on PRs, this should make sure we don't encounter errors like this in future.
- @quid/react-date-picker
=> fix: missing @quid/theme dependency

packages/react-layouts/src/Breadcrumb/__snapshots__/index.test.js.snap, packages/react-layouts/src/Breadcrumb/index.js, packages/react-layouts/src/Breadcrumb/index.test.js
Adds support for a new `renderArrowIcon` property, that allows to define a render function that returns a custom separator node we want to use. It will take precedence over an existing `arrowIcon` property.
=> feat: add renderArrowIcon support to Breadcrumb

packages/merge-refs/README.md, packages/merge-refs/package.json, packages/merge-refs/src/index.js, packages/merge-refs/src/index.test.js, packages/react-forms/package.json, packages/react-forms/src/InputDate/index.js, packages/react-forms/src/InputFile/index.js, packages/react-forms/src/InputText/index.js, src/badges.json
Publish `merge-refs` from its own package, so that we can reuse it easily between projects.
- @quid/merge-refs
=> feat: move merge-refs to a dedicated package

packages/merge-refs/package.json, packages/react-core/package.json, packages/react-date-picker/package.json, packages/react-dropdown/package.json, packages/react-ellipsis/package.json, packages/react-forms/package.json, packages/react-invalid-handler/package.json, packages/react-layouts/package.json, packages/react-mouse-outside/package.json, packages/react-package-template/init/package.json, packages/react-tabs-provider/package.json, packages/stylis-plugin-focus-visible/package.json, packages/theme/package.json
All our packages had been publish manually the first time because we previously hosted them on the internal registry.
Now, new packages, when published for the first time, required the access to be set to public to not fail the publish step.
This will fix the failed merge-refs publish.
- @quid/merge-refs
=> fix: set all packages to public by default

packages/react-layouts/src/Modal/index.js
Fixes an issue with the modal overlay, when used in consumer projects, the overlay didn't have a background color.
=> fix: modal overlay issue

package.json, packages/react-core/package.json, packages/react-forms/package.json, packages/react-layouts/package.json, yarn.lock
v5 is backward compatible with v4
=> fix: support React Router v5

packages/react-layouts/src/Modal/index.js
The semicolon was in the wrong position and was stripped out when the bundle was compiled.
=> fix: modal backdrop missing semicolon

packages/theme/fonts/ibmplex/index.css, packages/theme/fonts/icons/index.css
I changed the `font-display` value to `swap` (rather than `auto`), this should reduce the time to first render.
The idea came from [this tweet](https://twitter.com/samccone/status/1106979581876035584)
- @quid/theme
=> perf: reduce time to first render with font-display: swap

packages/react-dropdown/src/__mocks__/DropdownWrapper.js, packages/react-dropdown/src/index.js, packages/react-dropdown/src/index.md, packages/react-dropdown/src/index.test.js
This property allows to define a custom rendering logic for the dropdown component.
=> feat: add `renderDropdown` prop to react-dropdown

packages/react-dropdown/package.json, packages/react-dropdown/src/Items.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap, packages/react-dropdown/src/index.test.js, packages/react-forms/src/InputDate/__snapshots__/index.test.js.snap, packages/react-forms/src/InputText/__snapshots__/index.test.js.snap, packages/react-forms/src/InputText/index.js, yarn.lock
Change the styling colors of the react-dropdown to component to match the Quid UI [style guide](https://www.figma.com/file/LS5LEaS62tZITxOpSpDBXEeG/Master?node-id=70%3A10) more closely. 
Before: 
After: 
=> Feat dropdown change dark theme colors

packages/react-core/src/Button/Button.md, packages/react-core/src/Button/__snapshots__/index.test.js.snap, packages/react-core/src/Button/index.js
This fixes an issue where an Icon component inside a Button component wasn't properly aligned if the Icon was on the right of the text.
=> fix: properly space Icon when inside Button

packages/react-core/src/Button/__snapshots__/index.test.js.snap, packages/react-core/src/Button/index.js, packages/react-popover/README.md, packages/react-popover/package.json, packages/react-popover/src/__snapshots__/index.test.js.snap, packages/react-popover/src/index.js, packages/react-popover/src/index.md, packages/react-popover/src/index.test.js, packages/react-use-controlled-state/README.md, packages/react-use-controlled-state/package.json, packages/react-use-controlled-state/src/index.js, packages/react-use-controlled-state/src/index.test.js, packages/theme/src/themes/dark.js, packages/theme/src/themes/light.js, yarn.lock
This PR introduces two new packages:
- `@quid/react-use-controlled-state`
- `@quid/react-popover`
It also fixes an issue inside `@quid/theme`and a `ref` issue with Button.
- @quid/react-use-controlled-state
- @quid/react-popover
- @quid/theme
Internal ticket number: AF-597
=> feat: react-popover

styleguide.config.js
Something broken in the upgrade of styleguidist and CRA, building the app with the development config fixes the issue, it’s not optimal but it’s a viable workaround to fix the issue until I find a better solution.
=> fix: workaround for missing icons

packages/react-core/src/Button/__snapshots__/index.test.js.snap, packages/react-core/src/Button/index.js
restore PR #73, accidentally reverted by 9f0c810
=> fix: restore PR #73, accidentally reverted by 9f0c810

packages/react-core/src/Button/index.js, packages/react-core/src/Button/index.test.js
Fixes the `ref` property on `Button`
=> fix: forward Button “ref” property

packages/react-popover/README.md, packages/react-popover/package.json, packages/react-popover/src/index.js, packages/react-popover/src/index.md, packages/react-popover/src/index.test.js, packages/react-tooltip/README.md, packages/react-tooltip/package.json, packages/react-tooltip/src/__snapshots__/index.test.js.snap, packages/react-tooltip/src/index.js, packages/react-tooltip/src/index.md, packages/react-tooltip/src/index.test.js, yarn.lock
This PR adds two new functionalities to `Popover`: delays for open and close actions, and a way to have the popover listen for "mouse outside" events to close it.
Also, we now provide the `open` and `close` callbacks along with the pre-existing `toggle`.
On top of these changes, the Tooltip component have been added to the repository.
- @quid/react-popover
- @quid/react-tooltip
=> feat: Tooltip component

packages/react-popover/src/__snapshots__/index.test.js.snap, packages/react-popover/src/index.js, packages/react-popover/src/index.md, packages/react-popover/src/index.test.js
You can now define a `popover` property in the Emotion theme provider to override the `backgroundColor` and `borderColor` properties of the Popover and Tooltip Container and Arrow elements.
We can now easily override the Popover and Tooltip colors.
I also updated the default styles to match the spec.
- @quid/react-popover
- @quid/react-tooltip
=> feat: add theme support for Popover and Tooltip

packages/react-layouts/src/Breadcrumb/Breadcrumb.md, packages/react-layouts/src/Breadcrumb/index.js, packages/react-layouts/src/Breadcrumb/index.test.js
Adds `renderContent` function prop that has to return a `React.Node` to be able to customise the content of the Breadcrumb item without having a link wrapping the label. This change is backwards compatible.
=> feat: adds renderContent to BreadCrumb component

package.json, packages/react-forms/src/InputDate/index.test.js, yarn.lock
This PR upgrades react-scripts to latest so that they can work with node@12 (since 11 reached EOL).
- N/A
=> chore: react-scripts update to 3.x (fixes node 12)

packages/react-expandable-table/src/styles.js
Without this fix, consumers have to manually define the `*, *::before, *::after { box-sizing: none; }` in their application.
- @quid/react-expandable-table
=> fix: set box-sizing to ExpandableTable cell

packages/react-dropdown/package.json
Now we allow a wider version range for the @emotion/styled-base dependency.
This allows consumers to use a single version for several packages that rely on the same dependency.
=> fix: loosen emotion/styled-base version requirement

packages/react-forms/src/InputDate/InputDateWithCalendar.test.js, packages/react-forms/src/InputDate/index.js
User could type in an invalid date date would cause error. This adds handling for those cases.
Not sure if test is needed.
- @quid/react-forms - InputDate
=> (AF-978) fix: checks if the current is valid for the InputDate

packages/react-forms/src/InputNumber/index.js, packages/react-forms/src/InputNumber/index.test.js
Previously if you clicked on the InputNumber arrows, the `change` event wasn't triggered.
=> fix: trigger change event on InputNumber step up/down

packages/react-forms/package.json, packages/react-forms/src/InputRange/Handle.js, packages/react-forms/src/InputRange/InputRange.md, packages/react-forms/src/InputRange/__snapshots__/index.test.js.snap, packages/react-forms/src/InputRange/index.js, packages/react-forms/src/InputRange/index.test.js, packages/react-forms/src/InputRange/styles.js, packages/react-forms/src/InputRange/utils.js, yarn.lock
Replaced the InputRange implementation with `react-range`, performance is improved, and the controlled behavior is now fixed.
BREAKING CHANGE: the InputRange “value” property has been replaced by a “values” property that takes an array rather than an object.
This is to reflect the react-range API, which actually makes more sense and it's easier to use.
=> fix: controlled InputRange and performance improvements

packages/react-popover/package.json, yarn.lock
This PR updates the use-debounce dependency.
- @quid/react-popover
=> fix(dependency-update): updated use-debouce

packages/react-forms/src/InputDate/index.js
Adds a new `popperProps` property to `InputDate` to allow to override the react-popper configuration.
=> feat: allow to override InputDate Popper.js props

packages/react-dropdown/src/Categories.js, packages/react-dropdown/src/Items.js, packages/react-dropdown/src/List.js, packages/react-dropdown/src/MultiDownshift.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap, packages/react-dropdown/src/dropdownTypes.js, packages/react-dropdown/src/index.js, packages/react-dropdown/src/index.md, packages/react-dropdown/src/index.test.js
BREAKING CHANGE: onSelect callback's first param is now array instead of object
Now `multiselect` `true` enables user to select every option by clicking on the category.
=> feat: adds dropdown category selection option

packages/react-dropdown/src/MultiDownshift.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap, packages/react-dropdown/src/index.js, yarn.lock
Applying value in the dropdown was clearly a bad decision when multiselect is enabled, because it doesn't make sense. In case useFilter is applied it just messes up the list. I am sure in most cases there is a helper component that displays the values anyways.
Behaviour before:
& after:
=> fix: fixes dropdown multiple selection wrong behaviour for input value

packages/react-forms/src/InputCheckbox/index.test.js, packages/react-forms/src/utils/inputPropsFilters.js, packages/react-forms/src/utils/inputPropsFilters.test.js
=> fix: assign to checkbox only properties provided as props

packages/react-forms/src/InputNumber/index.js
This PR makes the arrows (up/down) of the InputNumber components visible only when the component is focused or hovered.
Also, I fixed a small issue that made the clickable area of one arrow overlap the other.
=> fix: show InputNumber arrows only when in use

packages/react-forms/src/InputCheckbox/index.js, packages/react-forms/src/InputRadio/index.js, packages/react-forms/src/InputText/index.js, packages/react-forms/src/InputToggle/index.js, packages/react-forms/src/index.js, packages/react-forms/src/index.test.js, packages/react-forms/src/utils/inputPropsFilters.js
This list is useful when you need to filter out/filter in component properties that need to be passed to children components.
I'm not exposing our `omit` and `include` implementations because I expect consumers to use their own set of utilities (such as lodash) and I don't want to have consumers rely on our internal implementations that may change, or get dropped all together in future.
=> feat: expose INPUT_ATTRIBUTES list

packages/react-expandable-table/src/index.js, packages/react-expandable-table/src/index.md, packages/react-expandable-table/src/index.test.js, packages/react-expandable-table/src/types.js, packages/react-expandable-table/src/utils.js
Adds support for passing React.Node in `data` to the ExpandableTable in the following way:
```
data: [
{
id: '4',
name: 'Black Widow',
rank: '4',
mentions: '17',
kol_score: '0.00%',
reach: '0.00%',
score: 800,
},
{
id: '5',
name: 'Hulk',
name: {
raw: 'Hulk',
content: <span style={{ color: 'gray' }}>Hulk</span>,
},
rank: '5',
mentions: '35',
kol_score: '99.10%',
reach: '99.10%',
score: 10,
},
```
`raw` is the raw value. It is needed to no break the sorting functionality. `content` could be a `React.Node` so you could style your component based on your need.
- @quid/react-expandable-table
=> feat: adds support for raw and content object in ExpandableTable

packages/react-expandable-table/src/index.js, packages/react-expandable-table/src/index.test.js, packages/react-expandable-table/src/types.js, packages/react-expandable-table/src/utils.js
- [] I updated the documentation and examples accordingly;
This is so we add backwards compatibility for ExpandableTable cell to be React.Node. It should not be used and probably will be removed in the future. I will migrate the code I know about that uses it.
- @quid/react-expandable-table
=> fix: backwards compatibility support for react node for the cell

packages/react-dropdown/src/Items.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap
change dropdown selected item background to aqua with 0.2 opacity
https://github.com/quid/frontend/issues/234
=> feat: change dropdown selected item background to aqua with 0.2 opacity

packages/react-core/src/Button/__snapshots__/index.test.js.snap, packages/react-core/src/Button/index.js
`props.theme.disabled` should be placed inside `wf()`
=> fix disabled button text color

packages/react-dropdown/src/Categories.js, packages/react-dropdown/src/Items.js, packages/react-dropdown/src/__snapshots__/index.test.js.snap
When scroll bar shows up, the item width exceeds the parent width since the width is not specified and passed down to children.
Set the width to 100% and child components can also set it to 100% so that the width can be adjusted based on the scroll bar is shown/hidden.
- Jira: https://jira.netbase.com/browse/QUID-27293
=> fix: react-dropdown width
